export const faceRegister = [
  {
    key: "donald",
    firstName: "Donald",
    lastName: "Trump",
    gender: "Male",
    dob: "14/06/1946",
    pob: "New York, United States",
    nationality: "United States",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "kim",
    firstName: "Kim",
    lastName: "Kardashain",
    gender: "Female",
    dob: "21/10/1980",
    pob: "Los Angeles, California, United States",
    nationality: "",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "cristiano",
    firstName: "Cristiano",
    lastName: "Ronaldo",
    gender: "Male",
    dob: "05/02/1985",
    pob: "Funchal, Portugal",
    nationality: "Portugal",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "oprah",
    firstName: "Oprah",
    lastName: "Winfrey",
    gender: "Female",
    dob: "29/01/1954",
    pob: "Kosciusko, Mississippi, United States",
    nationality: "",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "mohamed",
    firstName: "Mohamed",
    lastName: "Salah",
    gender: "Male",
    dob: "15/06/1992",
    pob: "Nagrig, Egypt",
    nationality: "",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "george",
    firstName: "George",
    lastName: "Timothy Clooney",
    gender: "Male",
    dob: "06/05/1961",
    pob: "Lexington, Kentucky, United States",
    nationality: "",
    wantedStatus: 0,
    wantedBy: "",
    charge: "",
    timeStamp: "Time"
  },
  {
    key: "carlos",
    firstName: "carlos",
    lastName: "ALVAREZ",
    photo: "./assets/img/placeholder1.jpg",
    gender: "Male",
    dob: "31/10/1971",
    pob: "Miami, Florida, United States",
    nationality: "United States",
    wantedStatus: 1,
    wantedBy: "Interpol",
    charge:
      "Conspiracy to Possess with Intent to Distribute Five Kilograms or More of Cocaine",
    timeStamp: "Time"
  },
  {
    key: "sergio",
    firstName: "sergio",
    lastName: "robles",
    photo: "./assets/img/placeholder1.jpg",
    gender: "Male",
    dob: "04/04/1982",
    pob: "Mexico",
    nationality: "Mexico",
    wantedStatus: 1,
    wantedBy: "Interpol",
    charge:
      "Conspiracy to possess with intent to distribute over 5 kilograms of cocaine",
    timeStamp: "Time"
  },
  {
    key: "raziiat",
    firstName: "raziiat",
    lastName: "utsumieva",
    photo: "./assets/img/placeholder1.jpg",
    gender: "Female",
    dob: "05/05/1979",
    pob: "BUYNAKSK TOWN, DAGESTAN REPUBLIC, Russia",
    nationality: "Russia",
    wantedStatus: 1,
    wantedBy: "Interpol",
    charge: "Participation in illegal armed formation",
    timeStamp: "Time"
  },
  {
    key: "marwan",
    firstName: "marwan",
    lastName: "sweidan",
    photo: "./assets/img/placeholder1.jpg",
    gender: "Male",
    dateOfBirth: "10/07/1987",
    placeOfBirth: "BEIRUT, Lebanon",
    nationality: "Lebanon",
    wantedStatus: 1,
    wantedBy: "Texas police department",
    charge: "sexual assualt",
    timeStamp: "Time"
  },
  {
    key: "geibi",
    first_name: "GEIBI",
    last_name: "KASSIM",
    gender: "Male",
    dob: "1966-07-01",
    pob: "Nagaf, Iraq",
    nationality: "Iraqi",
    wanted_by: "Belgium",
    wanted_status: 1,
    charge: "Theft with violence and with aggravating circumstances (murder)"
  },
  {
    key: "ramadan",
    first_name: "RAMADAN",
    last_name: "RAMADAN TAHER",
    gender: "Male",
    dob: "1987-08-26",
    pob: "Shikhan, Iraq",
    nationality: "Iraqi",
    wanted_by: "Sweden",
    wanted_status: 1,
    charge: "Murder"
  },
  {
    key: "qader",
    first_name: "QADER",
    last_name: "GARMIAN",
    gender: "Male",
    dob: "1997-08-27",
    pob: "Nagaf, Iraq",
    nationality: "Iraqi",
    wanted_by: "Sweden",
    wanted_status: 1,
    charge: "Kidnapping and murder."
  },
  {
    key: "alkhazarji",
    first_name: "NAZAR ABDELKARIM",
    last_name: "AL KHAZRAJI",
    gender: "Male",
    dob: "1985",
    pob: "Mosul, Iraq",
    nationality: "Iraqi",
    wanted_by: "Denmark",
    wanted_status: 1,
    charge: "War crimes"
  },
  {
    key: "carl",
    first_name: "CARL",
    last_name: "FREER",
    gender: "Male",
    dob: "1970",
    pob: "Sweden",
    nationality: "Swedish",
    wanted_by: "None",
    wanted_status: 0,
    charge: "None"
  }
  // ,
  // {
  //   "key": "jorge",
  //   "first_name": "JORGE",
  //   "last_name": "SEBASTIAO",
  //   "gender": "Male",
  //   "dob": "1965",
  //   "pob": "Portugal",
  //   "nationality": "Portugese",
  //   "wanted_by": "None",
  //   "wanted_status":0,
  //   "charge": "None"
  // },
  // {
  //   "key": "alex",
  //   "first_name": "ALEX",
  //   "last_name": "GADOTTI",
  //   "gender": "Male",
  //   "dob": "1969",
  //   "pob": "Italy",
  //   "nationality": "Italian",
  //   "wanted_by": "None",
  //   "wanted_status":0,
  //   "charge": "None"
  // }
];
